
// 81 pieces of furniture as of 1/18/23

const MickeyFurniture = [
    {
        furnitureName: `"An Apple a Day" Bowl`,
        price: 360,
        image: "/images/furniture/mickey&friends/_An_Apple_a_Day__Bowl.png",
        style: ["Casual","Rustic"],
        furnitureCategory: ["Kitchen","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Basic Dresser`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Basic_Dresser.png",
        style: ["Casual","Quirky"],
        furnitureCategory: ["Bedroom","Living Room","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Bedside Neon Decoration`,
        price: 2040,
        image: "/images/furniture/mickey&friends/Bedside_Neon_Decoration.png",
        style: ["Modern"],
        furnitureCategory: ["Bedroom","Living Room","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Berry Bowl`,
        price: 360,
        image: "/images/furniture/mickey&friends/Berry_Bowl.png",
        style: ["Casual"],
        furnitureCategory: ["Kitchen","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Biscuit Bowl`,
        price: 360,
        image: "/images/furniture/mickey&friends/Biscuit_Bowl.png",
        style: ["Casual"],
        furnitureCategory: ["Kitchen","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Blue Dining Chair`,
        price: 900,
        image: "/images/furniture/mickey&friends/180px-Blue_Dining_Chair.png",
        obtainedby: `Founder's Pack: Standard Edition`,
        style: ["Modern","Casual"],
        furnitureCategory: ["Dining Room","Kitchen","Seating"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Blue Dining Table`,
        price: 500,
        image: "/images/furniture/mickey&friends/180px-Blue_Dining-Table.png",
        obtainedby: `Founder's Pack: Standard Edition`,
        sstyle: ["Modern","Elegant"],
        furnitureCategory: ["Dining Room","Kitchen","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Cactus on a Pedatal`,
        price: 810,
        image: "/images/furniture/mickey&friends/74px=Cactus_on_a_Pedestal.png",
        style: ["Modern","Cute"],
        furnitureCategory: ["Bedroom","Kitchen","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Checker Board`,
        price: 360,
        image: "/images/furniture/mickey&friends/180px-Checker_Board.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Rec Room","Study","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Corner Counter`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Corner_Counter.png",
        style: [],
        furnitureCategory: ["Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Counter`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Counter.png",
        style: ["Modern","Casual"],
        furnitureCategory: ["Kitchen","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Cozy Armchair`,
        price: 900,
        image: "/images/furniture/mickey&friends/148px-Cozy_Armchair.png",
        style: ["Casual","Cute","Quirky"],
        furnitureCategory: ["Living Room","Seating"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Cozy Festive Hearth`,
        price: 600,
        obtainedby: `Festive Star Path`,
        image: "/images/furniture/mickey&friends/131px-Cozy_Festive_Hearth.png",
        style: ["Rustic", "Elegant"],
        furnitureCategory: ["Living Room","Study", "Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Cozy Fireplace`,
        price: 4000,
        image: "/images/furniture/mickey&friends/180px-Cozy_Fireplace.png",
        obtainedby: `Goofy Friendship Level 5`,
        style: ["Casual","Traditional"],
        furnitureCategory: ["Living Room","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Crowned Mickey Mouse Plant`,
        price: 810,
        image: "/images/furniture/mickey&friends/Crowned_Mickey_Mouse_Plant.png",
        style: ["Modern","Cute"],
        furnitureCategory: ["Bedroom","Study","Kitchen","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Cute Bow Bed`,
        price: 9200,
        image: "/images/furniture/mickey&friends/180px-Cute_Bow_Bed.png",
        obtainedby: `Minnie Mouse Friendship Level 8`,
        style: ["Cute","Casual"],
        furnitureCategory: ["Bedroom","Beds"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Cute Nightstand`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Cute_Nightstand.png",
        style: ["Rustic","Casual"],
        furnitureCategory: ["Bedroom","Living Room","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Cute Window`,
        price: 1500,
        image: "/images/furniture/mickey&friends/180px-Cute_Window.png",
        style: ["Cute","Rustic"],
        furnitureCategory: ["Kitchen","Bathroom","Windows"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Dark Wood Vintage Chest`,
        price: 3200,
        image: "/images/furniture/mickey&friends/180px-Dark_Wood_Vintage_Chest.png",
        obtainedby: `Player House or Scrooge's Store`,
        style: ["Tradional"],
        furnitureCategory: ["Bedroom","Study","Rec Room","Storage"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Dartboard`,
        price: 1200,
        image: "/images/furniture/mickey&friends/162px-Dartboard.png",
        style: ["Sporty","Casual"],
        furnitureCategory: ["Rec Room","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Dustbin`,
        price: 360,
        image: "/images/furniture/mickey&friends/180px-Dustbin.png",
        style: [],
        furnitureCategory: ["Kitchen","Bathroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Enchanted Broom`,
        price: 2400,
        image: "/images/furniture/mickey&friends/180px-Enchanted_Broom.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Kitchen","Outdoors","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Enchanting Bed`,
        price: 4600,
        image: "/images/furniture/mickey&friends/180px-Enchanting_Bed.png",
        style: ["Casual"],
        furnitureCategory: ["Bedroom","Beds"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Enchanting Fountain`,
        price: 20000,
        image: "/images/furniture/mickey&friends/180px-Enchanting_Fountain.png",
        obtainedby: `The Secret Door (Mickey Mouse Level 10)`,
        style: ["Elegany"],
        furnitureCategory: ["Outdoors","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Festive Dinner Table`,
        price: 660,
        image: "/images/furniture/mickey&friends/180px-Festive_Dinner_Table.png",
        obtainedby: `Festive Star Path`,
        style: ["Elegant","Traditional"],
        furnitureCategory: ["Dining Room","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Festive Garland`,
        // price: ,
        image: "/images/furniture/mickey&friends/180px-Festive_Garland.png",
        obtainedby: `Festive Star Path`,
        style: [],
        furnitureCategory: ["Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Festive Windows`,
        price: 480,
        image: "/images/furniture/mickey&friends/115px-Festive_Windows.png",
        obtainedby: `Festive Star Path`,
        style: ["Traditional","Elegant"],
        furnitureCategory: ["Dining Room","Study","Windows"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Festive Wreath Post`,
        price: 480,
        image: "/images/furniture/mickey&friends/92px-Festive_Wreath_Post.png",
        obtainedby: `Festive Star Path`,
        style: ["Rustic","Elegant"],
        furnitureCategory: ["Outdoors","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Garb Mannequin`,
        price: 6400,
        image: "/images/furniture/mickey&friends/180px-Garb_Mannequin.png",
        style: ["Cute"],
        furnitureCategory: ["Bedroom","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Grand Tree of Holiday Cheer`,
        price: 648,
        image: "/images/furniture/mickey&friends/117px-Grand_Tree_of_Holiday_Cheer.png",
        obtainedby: `Festive Star Path`,
        style: ["Traditional","Elegant"],
        furnitureCategory: ["Outdoors","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `L-Couch for Pals`,
        price: 6000,
        image: "/images/furniture/mickey&friends/180px-L-Couch_for_Pals.png",
        obtainedby: `Founder's Pack: Standard Edition`,
        style: ["Modern"],
        furnitureCategory: ["Living Room","Seating"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Lightwood Vintage Chest`,
        price: 3200,
        image: "/images/furniture/mickey&friends/180px-Light_Wood_Vintage_Chest.png",
        obtainedby: `Player House or Scrooge's Store`,
        style: ["Traditional"],
        furnitureCategory: ["Bedroom","Study","Rec Room","Storage"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Magnet Mania Fridge`,
        price: 3680,
        image: "/images/furniture/mickey&friends/104px-Magnet_Mania_Fridge.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Kitchen","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Ceiling Light`,
        price: 2720,
        obtainedby: "Founder's Pack: Standard Edition",
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Ceiling_Light.png",
        style: ["Modern","Cute"],
        furnitureCategory: ["Dining Room","Living Room","Bedroom","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Dresser`,
        price: 3200,
        obtainedby: "Goofy Friendship Level 8",
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Dresser.png",
        style: ["Modern","Elegant"],
        furnitureCategory: ["Living Room","Bedroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.1
    },
    {
        furnitureName: `Mickey Mouse Jack-O'-Lantern`,
        price: 431,
        obtainedby: "Villain's Star Path",
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Jack-O'-Lantern.png",
        style: ["Traditional","Rustic"],
        furnitureCategory: ["Living Room","Outdoors","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.1
    },
    {
        furnitureName: `Mickey Mouse Mirror`,
        price: 1200,
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Mirror.png",
        style: ["Casual","Cute"],
        furnitureCategory: ["Bathroom","Bedroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Painting`,
        price: 6800,
        image: "/images/furniture/mickey&friends/145px-Mickey_Mouse_Painting.png",
        style: ["Modern"],
        furnitureCategory: ["Bedroom","Living Room","Dining Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Photo Holder`,
        price: 1020,
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Photo_Holder.png",
        style: ["Cute","Modern"],
        furnitureCategory: ["Bedroom","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Photo in Small Frame`,
        price: 306,
        image: "/images/furniture/mickey&friends/116px-Mickey_Mouse_Photo_in_Small_Frame.png",
        style: ["Casual","Cute"],
        furnitureCategory: ["Bedroom","Living Room","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Pumpkin`,
        price: 431,
        obtainedby: `"Trick or Treat" Special Task`,
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Pumpkin.png",
        tracked: false,
        style: ["Traditional","Rustic"],
        furnitureCategory: ["Living Room","Outdoors","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.1,
        updated: 1.12
    },
    {
        furnitureName: `Mickey Mouse Wall Clock`,
        price: 1200,
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse_Wall_Clock.png",
        style: [],
        furnitureCategory: ["Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse Wall Sconce`,
        price: 306,
        image: "/images/furniture/mickey&friends/157px-Mickey_Mouse_Wall_Sconce.png",
        style: ["Rustic","Elegant"],
        furnitureCategory: ["Bathroom","Bedroom","Dining Room","Kitchen","Living Room","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse's Gloves Wardrobe`,
        price: 3200,
        obtainedby: "Scrooge McDuck Friendship Level 5",
        image: "/images/furniture/mickey&friends/180px-Mickey_Mouse's_Gloves_Wardrobe.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Bedroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Mickey Mouse's Photo Frame`,
        price: 306,
        image: "/images/furniture/mickey&friends/104px-Mickey_Mouse's_Photo_Frame.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Bedroom","Study","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0,
        updated: 1.2
    },
    {
        furnitureName: `Mickey Mouses's Rounded Photo Frame`,
        price: 306,
        image: "/images/furniture/mickey&friends/135px-Mickey_Mouse's_Rounded_Photo_Frame.png",
        style: ["Casual","Cute"],
        furnitureCategory: ["Bedroom","Living Room","Study","Fecor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Minimalistic Armchair`,
        price: 2400,
        obtainedby: "Founder's Pack: Standard Edition",
        image: "/images/furniture/mickey&friends/180px-Minimalistic_Armchair.png",
        style: ["Modern"],
        furnitureCategory: ["Living Room","Bedroom","Study","Seating"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Painted Vase`,
        price: 306,
        image: "/images/furniture/mickey&friends/119px-Painted_Vase.png",
        style: ["Elegant"],
        furnitureCategory: ["Dining Room","Living Room","Study"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Polka Dot Armchair`,
        price: 900,
        obtainedby: "Minnie Mouse Friendship Level 5",
        image: "/images/furniture/mickey&friends/180px-Polka_Dot_Armchair.png",
        style: ["Cute","casual","Modern"],
        furnitureCategory: ["Bedroom","Living Room","Seating"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Purple Oval Rug`,
        price: 480,
        image: "/images/furniture/mickey&friends/180px-Purple_Oval_Rug.png",
        style: [],
        furnitureCategory: ["Rugs"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Quirky Floor Lamp`,
        price: 765,
        image: "/images/furniture/mickey&friends/60px-Quirky_Floor_Lamp.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Dining Room","Living Room","Study","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Quirky Table Lamp`,
        price: 306,
        image: "/images/furniture/mickey&friends/180px-Quirky_Table_Lamp.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Bedroom","Living Room","Dining Room","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Rectangular Coffee Table`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Rectangular_Coffee_Table.png",
        style: ["Casual","Rustic"],
        furnitureCategory: ["Living Room","Study","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Rectangular Frame`,
        price: 1000,
        image: "/images/furniture/mickey&friends/Rectangular_Frame.png",
        style: ["Casual","Cute"],
        furnitureCategory: ["Living Room","Study","Bedroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Rectangular Rug`,
        price: 480,
        image: "/images/furniture/mickey&friends/180px-Rectangular_Rug.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Rec Room","Living Room","Study","Bedroom","Rugs"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Round Rug`,
        price: 480,
        image: "/images/furniture/mickey&friends/Round_Rug.png",
        style: ["Casual"],
        furnitureCategory: ["Bedroom","Living Room","Rec Room","Study","Rugs"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Rounded Coffee Table`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Rounded_Coffee_Table.png",
        style: [],
        furnitureCategory: ["Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Rounded Frame`,
        price: 1000,
        image: "/images/furniture/mickey&friends/Rounded_Frame.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Living Room","Study","Bedroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Santa's Gift-Laden Sleigh`,
        // price: ,
        obtainedby: "Festive Star Path",
        image: "/images/furniture/mickey&friends/180px-Santa's_Gift-Laden_Sleigh.png",
        style: [],
        furnitureCategory: ["Outdoors","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Scrooge McDuck Wall Sign`,
        price: 2720,
        obtainedby: `Scrooge McDuck's Grand Re-Opening (Story Quest)`,
        image: "/images/furniture/mickey&friends/180px-Scrooge_McDuck_Wall_Sign.png",
        style: ["Professional"],
        furnitureCategory: ["Study","Rec Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Scrooge McDuck's Spare Safe`,
        price: 16000,
        obtainedby: "The Treasure Hunt Part 2 (Scrooge McDuck Level 10)",
        image: "/images/furniture/mickey&friends/163px-Scrooge_McDuck's_Spare_Safe.png",
        style: ["Professional","Traditional"],
        furnitureCategory: ["Study","Storage"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Silly Area Rug`,
        price: 4000,
        obtainedby: "Founder's Pack: Standard Edition",
        image: "/images/furniture/mickey&friends/180px-Silly_Area_Rug.png",
        style: ["Cute","Modern"],
        furnitureCategory: ["Living Room","Study","Bedroom","Rugs"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Silly Bedside Table`,
        price: 1320,
        obtainedby: "Scrooge McDuck Friendship Level 2",
        image: "/images/furniture/mickey&friends/Silly_Bedside_Table.png",
        style: ["Elegant","Modern"],
        furnitureCategory: ["Study","Bedroom","Living Room","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Simple Fridge`,
        price: 1320,
        image: "/images/furniture/mickey&friends/105px-Simple_Fridge.png",
        style: [],
        furnitureCategory: ["Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Sink`,
        price: 1200,
        image: "/images/furniture/mickey&friends/169px-Sink.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Kitchen","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Small Bedside Lamp`,
        price:306,
        image: "/images/furniture/mickey&friends/102px-Small_Bedside_Lamp.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Bedroom","Dining Room","Living Room","Lighting"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Small Table`,
        price: 528,
        image: "/images/furniture/mickey&friends/180px-Small_Table.png",
        style: [],
        furnitureCategory: ["Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Snowy Festive Window`,
        price: 480,
        obtainedby: "Festive Star Path",
        image: "/images/furniture/mickey&friends/89px-Snowy_Festive_Window.png",
        style: ["Traditional","Elegant"],
        furnitureCategory: ["Study","Dining Room","Windows"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.2
    },
    {
        furnitureName: `Stove`,
        price: 1380,
        image: "/images/furniture/mickey&friends/180px-Stove.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Kitchen","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Sweet Abstract Painting `,
        price: 3400,
        image: "/images/furniture/mickey&friends/158px-Sweet_Abstract_Painting.png",
        style: ["Modern"],
        furnitureCategory: ["Dining Room","Bedroom","Study","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Tall Potted Plant`,
        price: 1079,
        image: "/images/furniture/mickey&friends/137px-Tall_Potted_Plant.png",
        style: ["Casual","Modern"],
        furnitureCategory: ["Kitchen","Dining Room","Living Room","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Tea Kettle`,
        price: 1033,
        image: "/images/furniture/mickey&friends/153px-Tea_Kettle.png",
        style: ["Cute","Rustic"],
        furnitureCategory: ["Kitchen","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Tiny Chair`,
        price: 675,
        image: "/images/furniture/mickey&friends/108px-Tiny_Chair.png",
        style: ["Cute","Casual"],
        furnitureCategory: ["Kitchen","Dining Room","Seating"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Top Cupboard`,
        price: 1200,
        image: "/images/furniture/mickey&friends/154px-Top_Cupboard.png",
        style: ["Casual","Rustic"],
        furnitureCategory: ["Kitchen","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Triangular Coffee Table`,
        price: 3520,
        obtainedby: "Founder's Pack: Standard Edition",
        image: "/images/furniture/mickey&friends/180px-Triangular_Coffee_Table.png",
        style: ["Modern","Cute"],
        furnitureCategory: ["Study","Living Room","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Vintage Phone`,
        price: 810,
        image: "/images/furniture/mickey&friends/180px-Vintage_Phone.png",
        style: ["Modern","Cute"],
        furnitureCategory: ["Study","Kitchen","Bedroom","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Wall Planter`,
        price: 810,
        image: "/images/furniture/mickey&friends/180px-Wall_Planter.png",
        style: ["Casual","Elegant"],
        furnitureCategory: ["Kitchen","Living Room","Dining Room","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Wooden Bookshelf`,
        price: 3200,
        image: "/images/furniture/mickey&friends/94px-Wooden_Bookshelf.png",
        style: ["Cute"],
        furnitureCategory: ["Living Room","Study","Decor"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Wooden End Table`,
        price: 1320,
        image: "/images/furniture/mickey&friends/180px-Wooden_End_Table.png",
        style: ["Casual","Rustic"],
        furnitureCategory: ["Bedroom","Living Room","Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    {
        furnitureName: `Wooden Side Table`,
        // price: ,
        image: "/images/furniture/mickey&friends/180px-Wooden_Side_Table_(2).png",
        style: [],
        furnitureCategory: ["Tables"],
        color: [],
        universe: "Mickey & Friends",
        added: 1.0
    },
    // {
    //     furnitureName: ``,
    //     price: ,
    //     image: "",
    //     style: [],
    //     furnitureCategory: [""],
    //     color: [],
    //     universe: "Mickey & Friends",
    //     added: 1.3
    // },
]

module.exports=MickeyFurniture